### ISSUE TITLE
How to run thisssssssssssssssssssssssssssss

### ISSUE THREAD

**Issue by FurqanNiazi** [Arya920/Career-Guidance-AI-bot#3]
Man tell me how to run this i have done everything now just want to run it ,tell me which file should i run just now so that i could start giving prompts

**Comment by 22r01a7319** [comment]
In which platform we need to run this

**Comment by Arya920** [comment]
@22r01a7319 you need to install the libraries in the requirements.txt file. You are good to go. Just run the streamlit app using the above mentioned code in the terminal.
